name: bharat_store
description: Offline Inventory, Billing & Analytics App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mobile_scanner: ^3.5.5
  http: ^1.1.2
  crypto: ^3.0.3
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  file_picker: ^8.1.4 
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  uuid: ^4.2.2
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true